import React from 'react'
import './UnderNavbar.css'



export default function UnderNavbar() {
  return (
    
    <div className="body">
	<p className="topic"> The AI Blog</p>

	<p className="content">
		We love A.I. and welcome you to our AI blog. There is so much going on in the field of AI and our goal is to keep you up-to-date in innovative, informative, and entertaining ways. We see this website as a form of digital art as all images and text were generated by artificial intelligence (with a little bit of human help). This AI blog is written and designed by impressive AIs, and humans merely perform copy & paste operations - we showcase the progress of AI capabilities on all fronts (text, image, video, audio, design, technology, education, etc).
	</p>
	<img className="img" src="./images/AI.png" alt=""/>	




    </div>
  )


}
